### ISSUE TITLE
Maps reset in 1.14.3

### ISSUE THREAD

**Issue by mercurialmusic** [SydMontague/ImageMaps#11]
I'm not sure if this is preventable, but all of the placed maps reset in 1.14.3 after using the --forceUpgrade startup flag. Everything seems to be working fine otherwise -- the plugin still loads and images can be placed (or replaced) normally after the fact. 

Still the best map plugin out there!

**Comment by Boy132** [comment]
It is most likely that the forceUpgrade removed the map data and thus you need to recreate all maps.

If you have a backup from the pre 1.14.3 map you could try copy the data folder from there to the new map folder. (untested)

**Comment by SydMontague** [comment]
I couldn't reproduce the problem on my local CraftBukkit 1.14.3 server, using the --forceUpgrade flag on a 1.13.2 world with maps. Have you tried what Boy132 suggested?

Also try updating your CraftBukkit/Spigot version if you haven't yet. Their 1.14 releases are still flagged as development builds to bugs and breakage is to be expected.

**Comment by mercurialmusic** [comment]
It was a good idea, but unfortunately loading the map data from a backup didn't work either, and I've been keeping up with the Spigot builds. I have a couple dozen worlds between my servers and it happened on all of them rather consistently, but perhaps I was doing something incorrectly. No matter, we're working on replacing them already -- it's not a huge issue. Hopefully I'll be the only one.
