### ISSUE TITLE
Cancellable map spawning event

### ISSUE THREAD

**Issue by GiraffeCubed** [SydMontague/ImageMaps#14]
Hello!

I've been using this plugin as my go-to image map tool for a while now, however, I use it as a donator perk on my server. I've created my own things like per-player map lists etc. but a common problem I have is that players can place the maps in any location, even if they don't have build permission there (via worldguard, griefprevention, etc.). It would be fantastic if there was a cancellable event fired in ImageMaps when someone tries to place an image map, this way I could check mysef if they have permission to build in this location, and if not - cancel the map from being placed.

Thanks!

**Comment by SydMontague** [comment]
Done https://github.com/SydMontague/ImageMaps/commit/0fc7586df3c5616b929f6eb1e4554cabd3ba549a

I haven't put it in a release yet, but I assume you're able to build the latest snapshot yourself. :)

**Comment by GiraffeCubed** [comment]
Thanks so much for this addtion, it's exactly what was needed, thank you!
