### ISSUE TITLE
giving others permissions

### ISSUE THREAD

**Issue by KingGobo** [SydMontague/ImageMaps#17]
Im trying to give my friends permissions to use all the commands but I dotn understand how you give that. could you maybe paste the slash command on how to do it or tell me if its another way. 
thanks

**Comment by SydMontague** [comment]
You will need a Permissions plugin like [LuckPerms](https://www.spigotmc.org/resources/luckperms.28140/). Use the documentation of the permission plugin of your choice on how to add/set permission nodes to users/groups.
