### ISSUE TITLE
/help error message

### ISSUE THREAD

**Issue by apaggioli** [SydMontague/ImageMaps#18]
I'm attempting to set the plugin up on my server — I use Shockbyte to host, and have tried to use their automated method to no avail. I then attempted to do so manually through Filezilla, and have found that an image folder isn't being created either. I'm extremely new to this, and don't really have a clue what to do any help is appreciated.

1.16.4 CraftBukkit server

**Comment by SydMontague** [comment]
Please use Spigot instead of plain CraftBukkit, it is the officially supported build and contains them additional features that are required to make this plugin work.

If that doesn't work please check your server log whether there are any errors on startup and paste them here.
