### ISSUE TITLE
error

### ISSUE THREAD

**Issue by ghost** [SydMontague/ImageMaps#2]
logs,
http://hastebin.com/opuwawelos.avrasm

**Comment by SydMontague** [comment]
What steps do you do to reproduce the error?
Have you tried it with an unmodified version of CraftBukkit/Spigot?

**Comment by ghost** [comment]
i am using https://tcpr.ca/downloads/paperspigot and
https://www.spigotmc.org/resources/asyncworldedit.327/
28 lut 2016 20:52 "SydMontague" notifications@github.com napisał(a):

**Comment by SydMontague** [comment]
Please try whether this error in an unmodified version of CraftBukkit and/or Spigot, as I'm unable to support 3rd party modifications.

I also can't reproduce it on a local server with only the plugin running.
