### ISSUE TITLE
Permission to stop people breaking placed maps

### ISSUE THREAD

**Issue by t0mtee** [SydMontague/ImageMaps#21]

**Comment by t0mtee** [comment]
It would also be good to make it so breaking one part of the map breaks all of it and it drops only one item frame and all of the maps disappear

**Comment by SydMontague** [comment]
The plugin doesn't memorize where maps are placed, only what map represents what part of the image. Your best option would be to protect the item frames via dedicated protection plugins.

**Comment by t0mtee** [comment]
Ok, thanks
