### ISSUE TITLE
"Map couldn't be placed, there is another entity in the way"

### ISSUE THREAD

**Issue by ThatPCDude** [SydMontague/ImageMaps#23]
Every time I try to place a map, which is a regular 128x128 PNG by the way, it gives this error:
[Sat, 13. Feb 2021 16:29:14 CET ERROR] Could not pass event PlayerInteractEvent to ImageMaps v1.0.3
And when I click the top-left thing it says "Map couldn't be placed, there is another entity in the way" while there isn't another entity to be found. I can't place any map now so I'm kind of stuck.

**Comment by ThatPCDude** [comment]
Oh I'm using Spigot 1.13.2 With ~35 other plugins^^

**Comment by SydMontague** [comment]
Can you post the entire stacktrace of the error?

**Comment by ThatPCDude** [comment]
Where can I find the stacktrace of the error? This is the only thing it shows in console. (By the way it also happens in 1.0.4)

**Comment by SydMontague** [comment]
Right below the "Could not pass event" message should be some more stuff

**Comment by ThatPCDude** [comment]
Couldn't find it in my discord chatbridge, but I was able to find it in my logs:
https://pastebin.com/sumtwPjG

**Comment by SydMontague** [comment]
Thanks, I was able to locate the issue and it should be fixed in 1.0.5

**Comment by ThatPCDude** [comment]
Cheers! Thanks for the super quick response and the quick fix :D
