### ISSUE TITLE
Images not showing up

### ISSUE THREAD

**Issue by skytcosplay** [SydMontague/ImageMaps#25]
I am uploading images, and i am doing everything how it is supposed to be done and yet anytime I try and use them in my server t says that an image with that name doesnt exist. Even though it clearly does. I am just getting so frusterated and tired

**Comment by SydMontague** [comment]
Do your file names contain spaces? If so either rename the files to not contain spaces or put the image name in "", like this:

/imagemaps place "image with spaces.png"

**Comment by skytcosplay** [comment]
I tried that and it still says that it doesnt exist

**Comment by SydMontague** [comment]
What's the name of your image?

**Comment by skytcosplay** [comment]
uuh the tester one is lilsis.png

**Comment by skytcosplay** [comment]
Im sorry haha, I just really want this to work

**Comment by SydMontague** [comment]
Is the image being listed in `/imagemap list` or as an option for tab complete in `/imagemap place`?

**Comment by skytcosplay** [comment]
yes it is an option on both, however when i click it it says that the image does not exist. I have uploaded it to the file that was needed, and I saved it.

**Comment by SydMontague** [comment]
Is there anything in your server log when you get this error message?

**Comment by skytcosplay** [comment]
How do you mean

**Comment by skytcosplay** [comment]
I FIGURED IT OUT- I figured it out. Sorry thank you haha

**Comment by SydMontague** [comment]
What was the issue?
