### ISSUE TITLE
"Map couldn't be placed, there's another entity in the way" on Mohist Server

### ISSUE THREAD

**Issue by dylanspersad** [SydMontague/ImageMaps#26]
I'm currently using the latest version of both the mohist server and the image map plugin 

https://pastebin.pl/view/4081fd01

**Comment by SydMontague** [comment]
This seems like a problem with your server software failing to create a map.

**Comment by JamBlueberry** [comment]
> This seems like a problem with your server software failing to create a map.

Version
1.16.5 (629)

i have the same issue
 
so what now ? do we ask the  Mohistmc form ?

**Comment by SydMontague** [comment]
Yeah, I think it's a good idea asking the authors of the server software. The error doesn't happen on base Spigot, so it's very likely that it's caused by some change they made.

**Comment by JamBlueberry** [comment]
ok i made a post on ther https://forum.mohistmc.com/d/40-imagemaps-brakes-on-mohist

**Comment by SydMontague** [comment]
An interesting development, the error is now happening on stock Spigot 1.17 (but not 1.16.5) due to a change in Mojang code...

https://hub.spigotmc.org/jira/browse/SPIGOT-6510

**Comment by Shizzins** [comment]
> An interesting development, the error is now happening on stock Spigot 1.17 (but not 1.16.5) due to a change in Mojang code...
> 
> https://hub.spigotmc.org/jira/browse/SPIGOT-6510

will there be an ETA for the 1.17 version of the plugin? I reall love your work

**Comment by SydMontague** [comment]
As long as you're using a Spigot version build after the 12th of June the plugin should be fully compatible with 1.17. 

Under ideal circumstances it is unnecessary for Spigot plugins to get updated to a new Minecraft version.

**Comment by Shizzins** [comment]
> As long as you're using a Spigot version build after the 12th of June the plugin should be fully compatible with 1.17.
> 
> Under ideal circumstances it is unnecessary for Spigot plugins to get updated to a new Minecraft version.

The plugin works, but it keeps saying there is an entity in the way and the maps will not place and instead places a single empty item frame

**Comment by SydMontague** [comment]
Which means you don't have a Spigot version built after the 12th of June. Please update your Spigot.

**Comment by SydMontague** [comment]
Since this is almost certainly a server software issue and not a plugin issue I'm gonna close this...
