### ISSUE TITLE
1.17 is not supported

### ISSUE THREAD

**Issue by vaporvee** [SydMontague/ImageMaps#35]
Sorry i think you are getting this enough but how long could it take until the plugin is working in 1.17?
Great plugin btw

**Comment by SydMontague** [comment]
The plugin should work fine with 1.17, or have you run into any bugs?

**Comment by vaporvee** [comment]
Since when? Did i miss an update? I can't place an image map just the commands work but when i want to place one it only places one empty item frame with luck

**Comment by SydMontague** [comment]
Are you getting any error messages in chat or in log? The plugin should not need to be updated specifically for 1.17.

Also, please make sure you're running the latest Spigot version. The early 1.17 builds had a bug that affected this plugin.

**Comment by vaporvee** [comment]
I try it in a few hours when i have time

**Comment by vaporvee** [comment]
So i don't know why it works i don't think i've updated but it works now and definitely didn't work at some point in the 1.17
