### ISSUE TITLE
Thermos/Tekkit Legends - Error

### ISSUE THREAD

**Issue by ghost** [SydMontague/ImageMaps#4]
thermos version
Thermos-1.7.10 - 1614.46.zip 
https://tcpr.ca/downloads/thermos 

tekkit modpack version
tekkit legends 1.7.10 - version 1.1.1
http://www.technicpack.net/modpack/tekkit-legends.735902

plugin version
ImageMaps v0.4.3

logs
http://hastebin.com/etivubohej.avrasm

**Comment by SydMontague** [comment]
1.7.10 isn't supported by this version of the plugin anymore. 

Please use version 0.4.1, which has no difference except for 1.9 compatibility.

**Comment by ghost** [comment]
ok
