### ISSUE TITLE
cant change permissions 

### ISSUE THREAD

**Issue by tem1312** [SydMontague/ImageMaps#43]
I run a spigot 1.17.1 server and I can't change any permissions all I see in the config folder is  toggleItem: WOODEN_HOE
and thats it

**Comment by SydMontague** [comment]
You have to manage permissions in your permissions plugin, e.g. LuckPerms.

**Comment by tem1312** [comment]
ah ok thanks

**Comment by tem1312** [comment]
still new to this, i have luck perms so how would i make it so everyone can use it, sorry for bothering

**Comment by SydMontague** [comment]
Add the permission nodes from the README to the default group (or whoever you want to be able to use it).

Be careful though, especially the download permission allows users to download files onto your server. This can be a security and legal risk and only be given to people you actually trust.

**Comment by tem1312** [comment]
ok thanks for your time
