### ISSUE TITLE
Size and Scale options

### ISSUE THREAD

**Issue by driahva** [SydMontague/ImageMaps#44]
An old forum post suggested that scale on placement was done with "[filename] scale int".  However this doesn't seem to work.  Your documentation doesn't offer an example of usage for the commands, and multiple attempts have failed.  Could you please elaborate on: `/imagemap place <filename> [frameInvisible] [frameFixed] [frameGlowing] [size]`?

**Comment by SydMontague** [comment]
/imagemap place <yourImage> false false false 5x5

Scales the image to up to 5x5, respecting the aspect ratio of the input image (i.e. 256x128 image will always be twice as many item frames wide as tall)

**Comment by driahva** [comment]
Thank you for the extremely fast response!
