### ISSUE TITLE
One colour maps

### ISSUE THREAD

**Issue by Dzikii81** [SydMontague/ImageMaps#47]
So i tried making a whole blue/cyan map, after downloading it i place the one coloured map and it either turns whole black for blue colour or whole white map for cyan colour

This colour black supposed to be blue
![image_2021-09-09_204027](https://user-images.githubusercontent.com/90419222/132751885-adb7606e-265f-405e-8faa-4d21f9501a1f.png)

this blue:
https://i.imgur.com/7ZMl5q8.png

**Comment by SydMontague** [comment]
This seems to be a problem related to the internal scaling. I recommend you just prepare the image in the desired resolution right away (128x128 per block), this should resolve the problem.

**Comment by Dzikii81** [comment]
i tried it earlier with different resolutions including 128x128, but did not work :/

**Comment by Dzikii81** [comment]
weird, before when i tried it, it did not want to work, anyway thanks!
