### ISSUE TITLE
Error: Can't place image here!

### ISSUE THREAD

**Issue by RebeccaRedstone** [SydMontague/ImageMaps#5]
Hi! Love the idea behind this plugin and I really want to get it to work! 
I have tried a 640X512 and it tells me "Can't place image here! Make sure the area is large enough, unobstructed and without preexisting hanging entities" I tried a 128X128 and it gave me the same error. 

I have tried doing this on a dirt wall in the middle of an open field and still get the error. 

Any help would be appreciated!

**Comment by SydMontague** [comment]
What Version of Minecraft and the Plugin are you using?

Also, is there some message in the server log when this error occures?

**Comment by RebeccaRedstone** [comment]
Using 1.9 minecraft and spigot 1.9 build from about 4 days ago? 

It is giving me an error in the log! didn't think to check that. It is saying;

10:29:48] [Server thread/INFO]: RebeccaRedstone issued server command: /imagemap test
[10:29:50] [Server thread/ERROR]: [ImageMaps] Someone tried to create an image with an invalid file!
[10:29:59] [Server thread/INFO]: RebeccaRedstone issued server command: /imagemap test
[10:30:00] [Server thread/ERROR]: [ImageMaps] Someone tried to create an image with an invalid file!

Any ideas how I could fix this? my file is called text and is a .png 
Thanks so much for your quick response!

**Comment by RebeccaRedstone** [comment]
Sorry, typo there! I mean my file is called test.png

**Comment by SydMontague** [comment]
You need to add the file extension to the command. 

-> /imagemap test.png

**Comment by RebeccaRedstone** [comment]
That helped a lot! I was not doing that! Seems like such a silly mistake!

Thanks for all of your help! I love this plugin! :dancer:

**Comment by SydMontague** [comment]
Revolved.
