### ISSUE TITLE
Images that worked perfectly fine before upgrading to 1.12 now show up with transparent pixels

### ISSUE THREAD

**Issue by PlasmaPod** [SydMontague/ImageMaps#6]
![12995048020851556352_screenshots_20170612194907_1](https://user-images.githubusercontent.com/6870751/27028562-780e8a9a-4fa8-11e7-9929-4017bb0c3f8b.jpg)

**Comment by PlasmaPod** [comment]
btw it worked perfectly all the way up to 1.11.2

**Comment by SydMontague** [comment]
It works fine on my server. I found [this commit](https://hub.spigotmc.org/stash/projects/SPIGOT/repos/craftbukkit/commits/f85977ae6f4ca213347d04c48cc93058ed742db5) that could be related, so I'd recommend updating your server and check if that fixes the problem.

**Comment by PlasmaPod** [comment]
Thanks will try this afternl

**Comment by PlasmaPod** [comment]
Yes so at the time my issue was created the spigot revision at that time caused it to happen but upon updating the spigot from buildtools today it is working correctly so the plugin is working correctly on 1.12 and thanks for your response
