### ISSUE TITLE
Imagemaps not downloading image (HTTP error code 429)

### ISSUE THREAD

**Issue by Booly2477** [SydMontague/ImageMaps#67]
Hey, whenever i try to download an image to imagemaps, it always shows the HTTP error 429

i have formatted the link, and it still doesn't work

https://i.imgur.com/Z4aiutF.png <- the image im attempting to download

**Comment by SydMontague** [comment]
HTTP 429 stands for "Too Many Requests", meaning the webserver you're trying to download from is blocking your download request. 

It might work if you wait a bit before trying again, typically it is a rate limit of requests.

**Comment by Booly2477** [comment]
it still won't work :[

**Comment by SydMontague** [comment]
Try a different image host.
