### ISSUE TITLE
Can't place new image with 1.13

### ISSUE THREAD

**Issue by Bobcat00** [SydMontague/ImageMaps#8]
Using ImageMaps 0.4.3 on 1.13 CraftBukkit version git-Bukkit-49a2604.  Images remaining from the previous server version display properly, but new images don't.  The /imagemap (file) true command works and there are no errors in the console, but the displayed image appears to be an image of an item frame (one per block) or maybe they're item frames in item frames.

I hope you're still maintaining this plugin and can update it.

**Comment by SydMontague** [comment]
I pushed a 0.4.4 version that should fix it.

**Comment by Bobcat00** [comment]
Works now.  Thanks!
